name: String to JSON
description: Convert a string to a JSON list
# author: ubuntu-robotics-community
# branding:
#   icon: trending-up
#   color: orange

inputs:
  string:
    default: ''
    description: "The input string to convert to a JSON list."
    required: true

outputs:
  json:
    description: "The input turned into a JSON list."
    value: ${{ steps.string-to-json.outputs.json }}

runs:
  using: composite
  steps:
    - name: String to JSON list
      shell: bash
      id: string-to-json
      env:
        INPUT: ${{ inputs.string }}
      run: |
        if [ -z "${INPUT}" ]; then
          echo "Input is not set!"
          exit 1
        fi

        input_json="${INPUT}"
        if ! jq -e . >/dev/null 2>&1 <<< "${INPUT}"; then
          input_json="[\"${INPUT}\"]"
          if ! jq -e . >/dev/null 2>&1 <<< "${input_json}"; then
            echo "Failed to JSONify '${INPUT}': '${input_json}'."
            exit 1
          fi
        fi
        echo "json=${input_json}" >> $GITHUB_OUTPUT
