name: _string-to-json
description: Convert a string to a JSON object

inputs:
  input:
    description: The input string
    required: true

outputs:
  json:
    description: The output JSON object
    value: ${{ steps.convert.outputs.json }}

runs:
  using: "composite"
  steps:

    - name: Install dependencies
      run: sudo apt-get install jq

    - name: Convert string to JSON
      id: convert
      env:
        input: ${{ inputs.input }}
      run: |
        input_as_json="${input}"
        if ! jq -e . >/dev/null 2>&1 <<< "${input}"; then
          echo "Input string '${input_as_json}' is not a JSON, formatting it into a JSON list."
          input_as_json="[\"${input}\"]"
        fi
        echo "json=${input_as_json}" >> $GITHUB_OUTPUT
