name: Jsonify

on:
  workflow_call:
    inputs:
      input:
        default: ''
        description: The input string to format as JSON.
        required: true
        type: string
    outputs:
      json:
        description: The input string formated as a JSON
        value: ${{ jobs.generate-snap-matrix.outputs.matrix }}

jobs:
  jsonify:
    runs-on: ubuntu-latest
    env:
      INPUT: ${{ inputs.input }}
    outputs:
      json: ${{ steps.jsonify.outputs.json }}
    steps:
      - name: Format input to JSON
        id: jsonify
        run: |
          if jq -e . >/dev/null 2>&1 <<< "${INPUT}"; then
            echo "runs-on=${INPUT}" >> $GITHUB_OUTPUT
          else
            input_as_json="[\"${INPUT}\"]"
            echo "ubuntu-image input is not a json, formatting it into a json list: $input_as_json."
            echo "runs-on=$input_as_json" >> $GITHUB_OUTPUT
          fi

