name: _runner-setup

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        description: The runner(s) to use formated as a string
        default: 'ubuntu-latest'
    outputs:
      runs-on:
        description: The runner(s) to use formated as a JSON
        value: ${{ jobs.setup.outputs.runs-on }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      runs-on: ${{ steps.convert.outputs.runs-on }}
    steps:
      - name: Convert to JSON
        id: convert
        env:
          input: ${{ inputs.runs-on }}
        run: |
          input_as_json="${input}"
          if ! jq -e . >/dev/null 2>&1 <<< "${input}"; then
            echo "Input is not a JSON, formatting it into a JSON list."
            input_as_json="[\"${input}\"]"
          fi
          echo "runs_on=${input_as_json}" >> $GITHUB_OUTPUT
