name: _runner-setup

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        description: The runner(s) to use formated as a string
        default: 'ubuntu-latest'
    outputs:
      runs-on:
        description: The runner(s) to use formated as a JSON
        value: ${{ jobs.setup.outputs.runs-on }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      runs-on: ${{ steps.set_variables.outputs.runs-on }}
    steps:
      - id: set_variables
        run: |
          if jq -e . >/dev/null 2>&1 <<< "$input"; then
            echo "runs-on=$input" >> $GITHUB_OUTPUT
          else
            input_as_json="[\"$input\"]"
            echo "ubuntu-image input is not a json, formatting it into a json list: $input_as_json."
            echo "runs-on=$input_as_json" >> $GITHUB_OUTPUT
          fi
        env:
          input: ${{ inputs.runs-on }}
