name: build

on:
  workflow_call:
    inputs:
      git-ref:
        default: '${{ github.ref }}'
        description: The branch to checkout.
        required: false
        type: string
      runs-on:
        default: 'ubuntu-latest'
        description: The runner(s) to use.
        required: false
        type: string
      snapcraft-args:
        default: ''
        description: The arguments to pass to snapcraft (pack).
        required: false
        type: string
      snapcraft-channel:
        default: 'latest/stable'
        description: The channel from which to install Snapcraft.
        required: false
        type: string
      snapcraft-enable-experimental-extensions:
        default: false
        description: Whether to enable Snapcraft experimental extensions or not.
        required: false
        type: boolean
      snapcraft-source-subdir:
        default: '.'
        description: The path where to execute snapcraft.
        required: false
        type: string

jobs:
  prepare-build-runners:
    runs-on: ubuntu-latest
    outputs:
      runs-on: ${{ fromJSON(steps.string-to-json.outputs.json) }}
    steps:
      - name: String to JSON list
        id: string-to-json
        uses: canonical/robotics-actions-workflows/string-to-json@fix/refactor-matrix
        with:
          string: ${{ inputs.runs-on }}

  prepare-build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.string-to-json.outputs.json }}
    steps:
      - name: String to JSON list
        id: string-to-json
        uses: canonical/robotics-actions-workflows/string-to-json@fix/refactor-matrix
        with:
          string: ${{ inputs.snapcraft-source-subdir }}

  build:
    needs: [prepare-build-runners, prepare-build-matrix]
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        source-subdir: ${{ fromJson(needs.prepare-build-matrix.outputs.matrix) }}
        runs-on: ${{ needs.prepare-build-runners.outputs.runs-on }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: '${{ inputs.git-ref }}'

      - name: Build snap
        uses: canonical/action-build@v1
        id: build-snap
        env:
          SNAPCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS: '${{ inputs.snapcraft-enable-experimental-extensions }}'
        with:
          path: '${{ matrix.source-subdir }}'
          snapcraft-channel: '${{ inputs.snapcraft-channel }}'
          snapcraft-args: '${{ inputs.snapcraft-args }}'

      - name: Set unique artifact name
        id: artifact-unique-name
        run: |
          echo "artifact-name=$(basename -s .snap ${{ steps.build-snap.outputs.snap }})" >> "$GITHUB_OUTPUT"

        #  echo "artifact-name=$(basename -s .snap ${{ steps.build-snap.outputs.snap }})-$(echo ${{ inputs.git-ref }} | sed "s|\/|\-|g")" >> "$GITHUB_OUTPUT"

      - name: Upload snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: '${{ steps.artifact-unique-name.outputs.artifact-name }}'
          path: '${{ steps.build-snap.outputs.snap }}'
          retention-days: 10
          if-no-files-found: error
