name: generic-upstream-monitor

on:
  workflow_call:
    inputs:
      git-ref:
        default: '${{ github.ref }}'
        description: The branch to checkout. Defaults to the current git ref.
        required: false
        type: string
      issue-assignee:
        default: ''
        description: The issue assignee in the form '@name'.
        required: false
        type: string
      script-compare-versions:
        description: A bash script to compare versions.
        required: true
        type: string
      script-get-upstream-version:
        description: A bash script to retrieve the upstream version.
        required: true
        type: string
      snapcraft-source-subdir:
        default: '.'
        description: The directory of the snapcraft project.
        required: false
        type: string

permissions:
  contents: read

concurrency:
  group: upstream-monitor-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  compare:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      issues: write
    steps:

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          ref: '${{ inputs.git-ref }}'

      - name: Parse snapcraft metadata
        id: parse
        uses: canonical/robotics-actions-workflows/parse-snapcraft-metadata@main
        with:
          snapcraft-source-subdir: ${{ inputs.snapcraft-source-subdir }}

      - name: Create get-upstream-version script
        shell: bash
        run: |
          cat > get-upstream-version << 'EOF'
            ${{ inputs.script-get-upstream-version }}
          EOF
          chmod +x get-upstream-version

      - name: Run get-upstream-version script
        id: get-upstream-version
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euxo pipefail
          version="$(./get-upstream-version)"
          if [ -z "${version}" ]; then exit 1; fi
          echo "upstream-version=${version}" >> "$GITHUB_OUTPUT"

      - name: Create script-compare-versions script
        shell: bash
        run: |
          cat > compare-versions << 'EOF'
            ${{ inputs.script-compare-versions }}
          EOF
          chmod +x compare-versions

      - name: Compare versions
        id: compare
        env:
          SNAP_VERSION: "${{ steps.parse.outputs.snap-version }}"
          UPSTREAM_VERSION: "${{ steps.get-upstream-version.outputs.upstream-version }}"
        run: |
          set -euxo pipefail
          NEW_RELEASE="$(./compare-versions "${UPSTREAM_VERSION}" "${SNAP_VERSION}")"
          echo "new-release=${NEW_RELEASE}" >> "$GITHUB_OUTPUT"

      - name: Open issue
        if: steps.compare.outputs.new-release == '1'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPSTREAM_VERSION: ${{ steps.get-upstream-version.outputs.upstream-version }}
          ISSUE_ASSIGNEE: ${{ inputs.issue-assignee }}
          TRIGGERING_ACTOR: ${{ github.triggering_actor }}
          GIT_REF: ${{ github.ref }}
          COMMIT_SHA: ${{ github.sha }}
          WORKFLOW_REF: ${{ github.workflow_ref }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        run: |
          search_issue="$(gh issue --repo "${REPO}" list --state open \
            --search "${UPSTREAM_VERSION} in:title" --json number)"

          if [[ ! "${search_issue}" =~ "number" ]]; then

            echo "Creating a new issue."

            extra_args=()
            if [ -n "${ISSUE_ASSIGNEE}" ]; then
              extra_args+=(--assignee "${ISSUE_ASSIGNEE}")
            fi

            echo -e "## Monitoring report\n\n" \
            "- Author: @${TRIGGERING_ACTOR}\n" \
            "- Branch: '${GIT_REF}'\n" \
            "- Commit: ${COMMIT_SHA}\n" \
            "- Workflow Path: '${WORKFLOW_REF}'\n\n" \
            "The workflow found a new version upstream: '${UPSTREAM_VERSION}'.\n" \
            "Please consider upgrading the snap.\n\n" \
            "Workflow details at: https://github.com/${REPO}/actions/runs/${RUN_ID}" \
            | \
            gh issue --repo "${REPO}" create \
              --title "[CI] Found version '${UPSTREAM_VERSION}' upstream" \
              "${extra_args[@]}" \
              --body-file -
          else
            echo "Issue already opened."
          fi
