name: simple-upstream-monitor

on:
  workflow_call:
    inputs:
      git-ref:
        default: '${{ github.ref }}'
        description: The branch to checkout. Defaults to the current git ref.
        required: false
        type: string
      snapcraft-source-subdir:
        default: '.'
        description: The path where to execute snapcraft. Defaults to '.'.
        required: false
        type: string
      source-repo:
        description: Repository of the source application in 'org/repo' form
        required: true
        type: string

jobs:
  compare:
    uses: canonical/robotics-actions-workflows/.github/workflows/upstream-monitor.yaml@feat/upstream-sync
    with:
      git-ref: ${{ inputs.git-ref }}
      #curl https://raw.githubusercontent.com/Ariel-Rodriguez/sh-semversion-2/refs/tags/v1.0.5/semver2.sh -o semver2.sh
      script-compare-versions: |
        wget https://raw.githubusercontent.com/Ariel-Rodriguez/sh-semversion-2/refs/tags/v1.0.5/semver2.sh -O semver2.sh
        chmod +x semver2.sh
        RET=$(./semver2.sh \"${UPSTREAM_VERSION}\" \"${SNAP_VERSION}\")
        if [ "${RET}" == "1" ]; then exit 1; fi
      # script-get-upstream-version: |
      #   TAG=$(curl -L \
      #     -H 'Accept: application/vnd.github+json' \
      #     -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
      #     -H 'X-GitHub-Api-Version: 2022-11-28' \
      #     https://api.github.com/repos/${{ inputs.source-repo }}/releases/latest \
      #     | jq -r 'select(.prerelease == false) | .tag_name')
      #   echo "${TAG}"
      script-get-upstream-version: echo "0.22.1"
      snapcraft-source-subdir: ${{ inputs.snapcraft-source-subdir }}
