name: snap

on:
  workflow_call:
    inputs:
      cleanup:
        description: Whether to cleanup the artifacts. Defaults to 'true'.
        required: false
        type: boolean
        default: true
      git-ref:
        default: '${{ github.ref }}'
        description: The branch to checkout. Defaults to the current git ref.
        required: false
        type: string
      lxc-image:
        description: The LXC image to run this action in.
        required: false
        type: string
      runs-on:
        default: 'ubuntu-latest'
        description: The runner(s) to use. Defaults to 'ubuntu-latest'.
        required: false
        type: string
      snap-install-args:
        default: "--dangerous"
        description: The argument to pass to snap install. Defaults to '--dangerous'.
        required: false
        type: string
      snap-test-script:
        description: A test script to run against the snap.
        required: false
        type: string
      snap-track:
        default: latest
        description: Snap Store channel track use for publication. Default to 'latest'.
        required: false
        type: string
      snapcraft-args:
        required: false
        type: string
      snapcraft-channel:
        default: 'latest/stable'
        description: The channel from which to install Snapcraft. Defaults to 'latest/stable'.
        required: false
        type: string
      snapcraft-enable-experimental-extensions:
        default: false
        description: Whether to enable Snapcraft experimental extensions or not. Defaults to false.
        required: false
        type: boolean
      snapcraft-source-subdir:
        default: '.'
        description: The path where to execute snapcraft. Defaults to '.'.
        required: false
        type: string
    secrets:
      snapstore-login:
        description: Snap Store credential (see 'snapcraft export-login').
        required: false

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      git-ref: ${{ inputs.git-ref }}
      runs-on: ${{ inputs.runs-on }}
      snapcraft-args: ${{ inputs.snapcraft-args }}
      snapcraft-channel: ${{ inputs.snapcraft-channel }}
      snapcraft-enable-experimental-extensions: ${{ inputs.snapcraft-enable-experimental-extensions }}
      snapcraft-source-subdir: ${{ inputs.snapcraft-source-subdir }}

  test:
    needs: [build]
    uses: ./.github/workflows/test.yaml
    with:
      lxc-image: ${{ inputs.lxc-image }}
      runs-on: ${{ inputs.runs-on }}
      snap-artifact: ${{ needs.build.outputs.snap-artifact-name }}
      snap-install-args: ${{ inputs.snap-install-args }}
      snap-test-script: ${{ inputs.snap-test-script }}

  publish:
    needs: [build, test]
    uses: ./.github/workflows/publish.yaml
    with:
      snap-artifact: ${{ needs.build.outputs.snap-artifact-name }}
      snap-track: ${{ inputs.snap-track }}
    secrets:
      snapstore-login: ${{ secrets.snapstore-login }}
    if: ${{ github.secret_source == 'Actions' }}

  cleanup:
    if: ${{ always() && !cancelled() && needs.build.result == 'success' && inputs.cleanup == true }}
    runs-on: ubuntu-latest
    needs: [build, publish]
    steps:
      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v4
        with:
          name: ${{ needs.build.outputs.snap-artifact-name }}
