name: snap

on:
  workflow_call:
    inputs:
      cleanup:
        default: true
        description: Whether to cleanup the artifacts.
        required: false
        type: boolean
      git-ref:
        default: '${{ github.ref }}'
        description: The branch to checkout.
        required: false
        type: string
      lxd-image:
        default: ''
        description: The LXC image to run this action in.
        required: false
        type: string
      runs-on:
        default: 'ubuntu-latest'
        description: The runner(s) to use.
        required: false
        type: string
      snap-install-args:
        default: "--dangerous"
        description: The argument to pass to snap install.
        required: false
        type: string
      snap-test-script:
        default: ''
        description: A test script to run against the snap.
        required: false
        type: string
      snap-track:
        default: latest
        description: Snap Store channel track use for publication.
        required: false
        type: string
      snapcraft-args:
        default: ''
        description: The arguments to pass to snapcraft (pack).
        required: false
        type: string
      snapcraft-channel:
        default: 'latest/stable'
        description: The channel from which to install Snapcraft.
        required: false
        type: string
      snapcraft-enable-experimental-extensions:
        default: false
        description: Whether to enable Snapcraft experimental extensions or not.
        required: false
        type: boolean
      snapcraft-source-subdir:
        default: '.'
        description: The path where to execute snapcraft.
        required: false
        type: string
    secrets:
      snapstore-login:
        description: Snap Store credential (see 'snapcraft export-login').
        required: false

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      git-ref: ${{ inputs.git-ref }}
      runs-on: ${{ inputs.runs-on }}
      snapcraft-args: ${{ inputs.snapcraft-args }}
      snapcraft-channel: ${{ inputs.snapcraft-channel }}
      snapcraft-enable-experimental-extensions: ${{ inputs.snapcraft-enable-experimental-extensions }}
      snapcraft-source-subdir: ${{ inputs.snapcraft-source-subdir }}

  test:
    needs: [build]
    uses: ./.github/workflows/test.yaml
    with:
      lxd-image: ${{ inputs.lxd-image }}
      runs-on: ${{ inputs.runs-on }}
      snap-install-args: ${{ inputs.snap-install-args }}
      snap-test-script: ${{ inputs.snap-test-script }}

  check-snapstore-login:
    runs-on: ubuntu-latest
    outputs:
      defined: ${{ steps.check.outputs.defined }}
    steps:
      - name: Check if Snapstore login is defined
        id: check
        # perform secret check & put boolean result as an output
        shell: bash
        run: |
          if [ "${{ secrets.snapstore-login }}" != '' ]; then
            echo "defined=true" >> $GITHUB_OUTPUT;
          else
            echo "defined=false" >> $GITHUB_OUTPUT;
          fi

  publish:
    needs: [build, test, check-snapstore-login]
    uses: ./.github/workflows/publish.yaml
    with:
      snap-track: ${{ inputs.snap-track }}
    secrets:
      snapstore-login: ${{ secrets.snapstore-login }}
    if: needs.check-snapstore-login.outputs.defined == 'true'

  # cleanup:
  #   if: ${{ always() && !cancelled() && needs.build.result == 'success' && inputs.cleanup == true }}
  #   runs-on: ubuntu-latest
  #   needs: [build, publish]
  #   steps:
  #     - name: Delete artifact
  #       uses: geekyeggo/delete-artifact@v4
  #       with:
  #         name: ${{ needs.build.outputs.snap-artifact-name }}
